**WorkSheet1**

Lakshya Gurung

In [ ]:
import numpy as np

One Dimensional array. (Note:- this is class tutorial, the Worksheet is a little further down below)

In [ ]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
a.ndim

1

In [ ]:
a.shape

(4,)

In [ ]:
type(a)

numpy.ndarray

Two dimensonal array

In [ ]:
a = np.array([[1,2,3,4],[4,6,8,9]])
a

array([[1, 2, 3, 4],
       [4, 6, 8, 9]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(2, 4)

Next One

In [ ]:
b = np.array([6,7,8,9])
b

array([6, 7, 8, 9])

In [ ]:
c = np.arange(12).reshape(3,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
c = np.arange(12).reshape(6,2)
c

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
d = np.ones([4,4])
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
e = np.eye(4)
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# New Array

In [ ]:
a = np.array([[4,5,6,7,8],[5,6,8,9,9]])
a

array([[4, 5, 6, 7, 8],
       [5, 6, 8, 9, 9]])

In [ ]:
b = np.array([[4,12,7,7,18],[5,2,0,9,5]])
b

array([[ 4, 12,  7,  7, 18],
       [ 5,  2,  0,  9,  5]])

In [ ]:
c = np.concatenate((a,b))
c

array([[ 4,  5,  6,  7,  8],
       [ 5,  6,  8,  9,  9],
       [ 4, 12,  7,  7, 18],
       [ 5,  2,  0,  9,  5]])

In [ ]:
c = np.concatenate((a,b), axis=1)
c

array([[ 4,  5,  6,  7,  8,  4, 12,  7,  7, 18],
       [ 5,  6,  8,  9,  9,  5,  2,  0,  9,  5]])

In [ ]:
d = np.add(a,b)
d

array([[ 8, 17, 13, 14, 26],
       [10,  8,  8, 18, 14]])

In [ ]:
d=np.hstack((a,b))
d

array([[ 4,  5,  6,  7,  8,  4, 12,  7,  7, 18],
       [ 5,  6,  8,  9,  9,  5,  2,  0,  9,  5]])

In [ ]:
d=np.vstack((a,b))
d

array([[ 4,  5,  6,  7,  8],
       [ 5,  6,  8,  9,  9],
       [ 4, 12,  7,  7, 18],
       [ 5,  2,  0,  9,  5]])

In [ ]:
b = np.array([[4,12,7,7,18],[5,2,0,9,5],[5,7,9,8,0]])
b

array([[ 4, 12,  7,  7, 18],
       [ 5,  2,  0,  9,  5],
       [ 5,  7,  9,  8,  0]])

# Example

In [ ]:
array = np.array([1,2,3])
array

array([1, 2, 3])

multiplies each element by 2, result: [2,4,6]

In [ ]:
new_array = array*2
new_array

array([2, 4, 6])

creeates a new array with the same elements

In [ ]:
copied_array = np.copy(array)
copied_array

array([1, 2, 3])

Slices elements from index 1 to 3 result: [2]

In [ ]:
sliced_array = array[1:2]
sliced_array

array([2])

In [ ]:
import numpy as np
import time

**The WorkSheet1 starts from here.**

4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy. Problem - 1: Array Creation: Complete the following Tasks:

Initialize an empty array with size 2X2.

In [ ]:
arr = np.empty((2, 2))
print(arr)

[[3.58976244e-315 0.00000000e+000]
 [5.31410685e-317 6.92604541e-310]]


Initialize an all one array with size 4X2.

In [ ]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
np.full((2, 3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

Problem - 2: Array Manipulation: Numerical Ranges and Array indexing: Complete the following tasks:

Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.


In [ ]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}

In [ ]:
arr = np.array([0,1,2,3,4,5,6,7,8])
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a random array of size 30 and find the mean of the array. {Hint:check for np.random.random() and array.mean() function}

In [ ]:
arr = np.random.randint(0,100, size = 30)
print(arr)
arr.mean()

[37 46 92 37 51 37 13 28  7 46 96 37 45 35 13 71 12 26 89 67 62 90 57 34
 54 53 33 71 19 38]


np.float64(46.53333333333333)

Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
arr = np.random.randint(0,100, size = (10,10))
print(arr)
print(arr.min())
print(arr.max())

[[36 53 42 70 73 23  5 63 94 47]
 [59 42 42 35 72 23 64 94  1 33]
 [ 9 13 94 25 50  6 84 98 67 69]
 [21 31  8 82 59 71  4 30 98 61]
 [21 22 41 33 30 63 81 37 89 25]
 [33 45 75 63 25 18  0 24 67 87]
 [74  5 10 55 86 27 91 12  8 50]
 [50 79  3 92 54 96 70 66 93 45]
 [ 2 58 58 46 96 74 93 98 71 75]
 [62 33 10 12 25 11 51 11 58 36]]
0
98


Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr = [1,2,0,0,4,0]
arr.reverse()
arr

[0, 4, 0, 0, 2, 1]

Create a 2d array with 1 on border and 0 inside.

In [ ]:
arr = np.zeros((5,5))
arr[0, :] = 1
arr[:, 0] = 1
arr[-1, :] = 1
arr[:, -1] = 1
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
arr = np.zeros((8,8))
for x in range(8):
    for y in range(8):
      if (x+y) % 2 == 0:
        arr[x,y] = 1
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


Add the two array.

In [ ]:
x = np.array([[1,3],[5,7]])
y = np.array([[5,4],[6,8]])
v = np.array([9,10])
w = np.array([11,12])

print(x+y)

[[ 6  7]
 [11 15]]


Subtract the two array.

In [ ]:
print(x-y)

[[-4 -1]
 [-1 -1]]


Multiply the array with any integers of your choice.

In [ ]:
print(2*x)

[[ 2  6]
 [10 14]]


Find the square of each element of the array.

In [ ]:
print(np.square(x))

[[ 1  9]
 [25 49]]


Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
print(np.dot(v,w))
print("\n")
print(np.dot(x,v))
print("\n")
print(np.dot(x,y))

219


[ 39 115]


[[23 28]
 [67 76]]


Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.}

In [ ]:
print(np.concatenate((x,y), axis = 1))
print("\n")
print(np.vstack((x,y)))

[[1 3 5 4]
 [5 7 6 8]]


[[1 3]
 [5 7]
 [5 4]
 [6 8]]


Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
np.concatenate((x, v))
# the number of input arrays must have same number of dimensions. Since the array at index 0 has 2 dimension(s), it pops up an error.

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Problem - 4: Matrix Operations: • For the following arrays: A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]); Prove following with Numpy:

Prove A.A−1 = I.

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
np.dot(A, np.linalg.inv(A))

array([[1.00000000e+00, 0.00000000e+00],
       [1.77635684e-15, 1.00000000e+00]])

Prove AB ̸= BA.

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
if np.array_equal(np.dot(A, B), np.dot(B, A)):
    print("False")
else:
    print("True")

True


Prove (AB)^T = B^T A^T

In [ ]:
np.array_equal(np.transpose(np.dot(A,B)), np.dot(np.transpose(B), np.transpose(A)))

True

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1 x − y + 2z = −3 3x + y − z = 9

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}

In [ ]:
A = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B = np.array([-1,-3,9])

inv_A = np.linalg.inv(A)
print(np.dot(inv_A, B))

[ 2.  1. -2.]


4.2 Experiment: How Fast is Numpy? In this exercise, you will compare the performance and implementation of operations using plain Python lists (arrays) and NumPy arrays. Follow the instructions:

Element-wise Addition: • Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.


In [ ]:
import time
import random

size = 1_000_000
list1 = [random.random() for _ in range(size)]
list2 = [random.random() for _ in range(size)]

start_time = time.time()

result = [list1[i] + list2[i] for i in range(size)]

end_time = time.time()

print("Time taken (Python lists):", end_time - start_time, "seconds")


Time taken (Python lists): 0.11252450942993164 seconds


 Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
import numpy as np
import time

size = 1_000_000
arr1 = np.random.rand(size)
arr2 = np.random.rand(size)

start_time = time.time()

result = arr1 + arr2

end_time = time.time()

print("Time taken (NumPy arrays):", end_time - start_time, "seconds")


Time taken (NumPy arrays): 0.025134563446044922 seconds


Element-wise Multiplication • Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea- sure and Print the time taken for this operation.

In [ ]:
size = 1_000_000
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

start = time.time()
list_result = [list1[i] * list2[i] for i in range(size)]
end = time.time()


print("Python List Time:", end - start, "seconds")

Python List Time: 0.1046900749206543 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
arr_result = arr1 * arr2
end = time.time()

print("NumPy Array Time:", end - start, "seconds")

NumPy Array Time: 0.002226114273071289 seconds


Dot Product • Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

In [ ]:
size = 1_000_000
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

start = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(size))
end = time.time()

print("Python List Dot Product Time:", end - start, "seconds")

Python List Dot Product Time: 0.10569357872009277 seconds


 Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
dot_numpy = np.dot(arr1, arr2)
end = time.time()

print("NumPy Dot Product Time:", end - start, "seconds")

NumPy Dot Product Time: 0.002985715866088867 seconds


Matrix Multiplication • Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [ ]:
n = 1000

A = [[random.random() for _ in range(n)] for _ in range(n)]
B = [[random.random() for _ in range(n)] for _ in range(n)]

C = [[0 for _ in range(n)] for _ in range(n)]

start_time = time.time()

for i in range(n):
    for j in range(n):
        total = 0
        for k in range(n):
            total += A[i][k] * B[k][j]
        C[i][j] = total

end_time = time.time()

print("Time taken (Python lists - 1000x1000 matrix multiplication):", end_time - start_time, "seconds")


KeyboardInterrupt: 

Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea- sure and print the time taken for this operation.

In [5]:
import numpy as np
import time

size = 1000   # define size first!

A_np = np.ones((size, size))
B_np = np.ones((size, size))

start = time.time()
C_np = np.dot(A_np, B_np)   # or A_np @ B_np
end = time.time()

print("NumPy Matrix Multiplication Time:", end - start, "seconds")


NumPy Matrix Multiplication Time: 0.22552824020385742 seconds
